### ISSUE TITLE
 TypeError: this.parseParameters is not a function

### ISSUE THREAD

**Issue by mcfedr** [hopin-team/twirp-ts#22]
In the release 2.3.1 I have this error - although when i built and used the main branch didn't have this issue.

```
--twirp_ts_out: TypeError: this.parseParameters is not a function
    at ProtobuftsPlugin.<anonymous> (/Users/mcfedr/projects/smartsuite/automation_engine/node_modules/twirp-ts/build/protoc-gen-twirp-ts/plugin.js:61:33)
    at Generator.next (<anonymous>)
    at /Users/mcfedr/projects/smartsuite/automation_engine/node_modules/twirp-ts/build/protoc-gen-twirp-ts/plugin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/mcfedr/projects/smartsuite/automation_engine/node_modules/twirp-ts/build/protoc-gen-twirp-ts/plugin.js:4:12)
    at ProtobuftsPlugin.generate (/Users/mcfedr/projects/smartsuite/automation_engine/node_modules/twirp-ts/build/protoc-gen-twirp-ts/plugin.js:60:16)
    at ProtobuftsPlugin.<anonymous> (/Users/mcfedr/projects/smartsuite/automation_engine/node_modules/@protobuf-ts/plugin-framework/build/commonjs/plugin-base.js:65:46)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/mcfedr/projects/smartsuite/automation_engine/node_modules/@protobuf-ts/plugin-framework/build/commonjs/plugin-base.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
make: *** [codegen_twirp_ts] Error 1
```

**Comment by fenos** [comment]
mmmmh... that is weird, can i see the `protoc` command you are using

it works fine to me on `2.3.1`

**Comment by fenos** [comment]
I've published `2.3.2` which updates the `@protobuf-ts/plugin-framework` with the fix of large files generators, try that and let me know.

Maybe also try to delete your `node_modules`

**Comment by fenos** [comment]
i see what happened, there was a breaking change pushed in the `@protobuf-ts/plugin-framework` which I haven't realized.

try using the latest version `2.3.3` it should have been fixed, I'll add some tests to catch this things earlier

**Comment by fenos** [comment]
I should also probably lock the dependency 😄
